# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bdef93e95bf4edf88ed30ce6ffe7181a1ffc377521c596b8c2b690a4dbd6cf0974e941f84b0048355b2f44c4f33a6f3a445508c525aa9a22e9bdd52b05afcabd

test:
  secret_key_base: 69b230ffbdab69ca3fee6b12aeeefa71a57028211e4136f7411e81a49a3f455531cf173040c9aeee5fa7e0ff14eb86096a5969e4bfce201ee181d3818171c9a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
